// This file is used when running GUI in dev mode.

// In production mode, this file will be generated by the server
// based on run-time parameters.

// Make changes to this if you want the GUI to connect to an OpenSpace instance
// with a different address/port combination than the defaults.

window.OpenSpaceEnvironment = {
    //wsAddress: '10.20.142.148',
    //wsPort: 4682
    //wsPort: 8001 
    wsAddress: 'http://localhost',
    wsPort: 8001
};
